export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      alerts: {
        Row: {
          id: string;
          house_id: string | null;
          alert_type: AlertType;
          priority: AlertPriority;
          title: string;
          message: string;
          related_entity_type: string | null;
          related_entity_id: string | null;
          is_read: boolean;
          is_dismissed: boolean;
          dismissed_by: string | null;
          dismissed_at: string | null;
          expires_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          house_id?: string | null;
          alert_type: AlertType;
          priority?: AlertPriority;
          title: string;
          message: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          is_read?: boolean;
          is_dismissed?: boolean;
          dismissed_by?: string | null;
          dismissed_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string | null;
          alert_type?: AlertType;
          priority?: AlertPriority;
          title?: string;
          message?: string;
          related_entity_type?: string | null;
          related_entity_id?: string | null;
          is_read?: boolean;
          is_dismissed?: boolean;
          dismissed_by?: string | null;
          dismissed_at?: string | null;
          expires_at?: string | null;
          created_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          table_name: string;
          record_id: string;
          action: AuditAction;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          table_name: string;
          record_id: string;
          action: AuditAction;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          table_name?: string;
          record_id?: string;
          action?: AuditAction;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      beds: {
        Row: {
          id: string;
          room_id: string;
          bed_number: number;
          bed_type: string | null;
          weekly_rent: number;
          bond_amount: number | null;
          status: BedStatus;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          bed_number: number;
          bed_type?: string | null;
          weekly_rent: number;
          bond_amount?: number | null;
          status?: BedStatus;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          bed_number?: number;
          bed_type?: string | null;
          weekly_rent?: number;
          bond_amount?: number | null;
          status?: BedStatus;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      bill_allocations: {
        Row: {
          id: string;
          bill_id: string;
          tenant_id: string;
          lease_id: string | null;
          days_in_period: number;
          occupant_count: number;
          allocated_amount: number;
          is_paid: boolean;
          paid_date: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          bill_id: string;
          tenant_id: string;
          lease_id?: string | null;
          days_in_period: number;
          occupant_count?: number;
          allocated_amount: number;
          is_paid?: boolean;
          paid_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          bill_id?: string;
          tenant_id?: string;
          lease_id?: string | null;
          days_in_period?: number;
          occupant_count?: number;
          allocated_amount?: number;
          is_paid?: boolean;
          paid_date?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      bills: {
        Row: {
          id: string;
          house_id: string;
          bill_type: BillType;
          provider: string | null;
          account_number: string | null;
          period_start: string;
          period_end: string;
          due_date: string;
          total_amount: number;
          split_mode: BillSplitMode;
          status: BillStatus;
          paid_date: string | null;
          file_path: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          bill_type: BillType;
          provider?: string | null;
          account_number?: string | null;
          period_start: string;
          period_end: string;
          due_date: string;
          total_amount: number;
          split_mode: BillSplitMode;
          status?: BillStatus;
          paid_date?: string | null;
          file_path?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          bill_type?: BillType;
          provider?: string | null;
          account_number?: string | null;
          period_start?: string;
          period_end?: string;
          due_date?: string;
          total_amount?: number;
          split_mode?: BillSplitMode;
          status?: BillStatus;
          paid_date?: string | null;
          file_path?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      bonds: {
        Row: {
          id: string;
          lease_id: string;
          tenant_id: string;
          house_id: string;
          expected_amount: number;
          received_amount: number;
          received_date: string | null;
          lodged_with: string | null;
          lodgement_reference: string | null;
          status: BondStatus;
          refund_amount: number | null;
          refund_date: string | null;
          deductions: Json;
          total_deductions: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          tenant_id: string;
          house_id: string;
          expected_amount: number;
          received_amount?: number;
          received_date?: string | null;
          lodged_with?: string | null;
          lodgement_reference?: string | null;
          status?: BondStatus;
          refund_amount?: number | null;
          refund_date?: string | null;
          deductions?: Json;
          total_deductions?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          tenant_id?: string;
          house_id?: string;
          expected_amount?: number;
          received_amount?: number;
          received_date?: string | null;
          lodged_with?: string | null;
          lodgement_reference?: string | null;
          status?: BondStatus;
          refund_amount?: number | null;
          refund_date?: string | null;
          deductions?: Json;
          total_deductions?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      candidates: {
        Row: {
          id: string;
          house_id: string | null;
          room_id: string | null;
          bed_id: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          preferred_move_in: string | null;
          budget_min: number | null;
          budget_max: number | null;
          occupation: string | null;
          employer: string | null;
          visa_status: string | null;
          current_situation: string | null;
          about_me: string | null;
          status: CandidateStatus;
          screening_score: number | null;
          screening_notes: string | null;
          converted_to_tenant: string | null;
          converted_at: string | null;
          source: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id?: string | null;
          room_id?: string | null;
          bed_id?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          preferred_move_in?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          occupation?: string | null;
          employer?: string | null;
          visa_status?: string | null;
          current_situation?: string | null;
          about_me?: string | null;
          status?: CandidateStatus;
          screening_score?: number | null;
          screening_notes?: string | null;
          converted_to_tenant?: string | null;
          converted_at?: string | null;
          source?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string | null;
          room_id?: string | null;
          bed_id?: string | null;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          preferred_move_in?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          occupation?: string | null;
          employer?: string | null;
          visa_status?: string | null;
          current_situation?: string | null;
          about_me?: string | null;
          status?: CandidateStatus;
          screening_score?: number | null;
          screening_notes?: string | null;
          converted_to_tenant?: string | null;
          converted_at?: string | null;
          source?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      checklist_items: {
        Row: {
          id: string;
          checklist_id: string;
          item_name: string;
          location: string | null;
          condition: ItemCondition;
          condition_notes: string | null;
          photo_path: string | null;
          requires_action: boolean;
          action_notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          checklist_id: string;
          item_name: string;
          location?: string | null;
          condition: ItemCondition;
          condition_notes?: string | null;
          photo_path?: string | null;
          requires_action?: boolean;
          action_notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          checklist_id?: string;
          item_name?: string;
          location?: string | null;
          condition?: ItemCondition;
          condition_notes?: string | null;
          photo_path?: string | null;
          requires_action?: boolean;
          action_notes?: string | null;
          created_at?: string;
        };
      };
      checklists: {
        Row: {
          id: string;
          lease_id: string;
          tenant_id: string;
          house_id: string;
          room_id: string | null;
          checklist_type: ChecklistType;
          status: ChecklistStatus;
          scheduled_date: string | null;
          completed_date: string | null;
          completed_by: string | null;
          tenant_signature: string | null;
          staff_signature: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          tenant_id: string;
          house_id: string;
          room_id?: string | null;
          checklist_type: ChecklistType;
          status?: ChecklistStatus;
          scheduled_date?: string | null;
          completed_date?: string | null;
          completed_by?: string | null;
          tenant_signature?: string | null;
          staff_signature?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          tenant_id?: string;
          house_id?: string;
          room_id?: string | null;
          checklist_type?: ChecklistType;
          status?: ChecklistStatus;
          scheduled_date?: string | null;
          completed_date?: string | null;
          completed_by?: string | null;
          tenant_signature?: string | null;
          staff_signature?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      cleaning_roster: {
        Row: {
          id: string;
          house_id: string;
          tenant_id: string;
          week_start: string;
          areas: string[];
          is_completed: boolean;
          completed_at: string | null;
          verified_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          tenant_id: string;
          week_start: string;
          areas: string[];
          is_completed?: boolean;
          completed_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          tenant_id?: string;
          week_start?: string;
          areas?: string[];
          is_completed?: boolean;
          completed_at?: string | null;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      expenses: {
        Row: {
          id: string;
          house_id: string;
          category: ExpenseCategory;
          description: string;
          amount: number;
          expense_date: string;
          is_recurring: boolean;
          recurrence_period: string | null;
          vendor: string | null;
          receipt_path: string | null;
          maintenance_ticket_id: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          category: ExpenseCategory;
          description: string;
          amount: number;
          expense_date: string;
          is_recurring?: boolean;
          recurrence_period?: string | null;
          vendor?: string | null;
          receipt_path?: string | null;
          maintenance_ticket_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          category?: ExpenseCategory;
          description?: string;
          amount?: number;
          expense_date?: string;
          is_recurring?: boolean;
          recurrence_period?: string | null;
          vendor?: string | null;
          receipt_path?: string | null;
          maintenance_ticket_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      house_rules_versions: {
        Row: {
          id: string;
          house_id: string;
          version: number;
          rules_content: string;
          effective_from: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          version: number;
          rules_content: string;
          effective_from: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          version?: number;
          rules_content?: string;
          effective_from?: string;
          created_by?: string | null;
          created_at?: string;
        };
      };
      houses: {
        Row: {
          id: string;
          name: string;
          address: string;
          suburb: string;
          postcode: string;
          state: string;
          country: string;
          property_manager: string | null;
          owner_name: string | null;
          owner_contact: string | null;
          total_bedrooms: number;
          total_beds: number;
          default_bond_weeks: number;
          default_bill_split_mode: BillSplitMode;
          prorate_move_in: boolean;
          prorate_move_out: boolean;
          wifi_ssid: string | null;
          wifi_password: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          address: string;
          suburb: string;
          postcode: string;
          state?: string;
          country?: string;
          property_manager?: string | null;
          owner_name?: string | null;
          owner_contact?: string | null;
          total_bedrooms?: number;
          total_beds?: number;
          default_bond_weeks?: number;
          default_bill_split_mode?: BillSplitMode;
          prorate_move_in?: boolean;
          prorate_move_out?: boolean;
          wifi_ssid?: string | null;
          wifi_password?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string;
          suburb?: string;
          postcode?: string;
          state?: string;
          country?: string;
          property_manager?: string | null;
          owner_name?: string | null;
          owner_contact?: string | null;
          total_bedrooms?: number;
          total_beds?: number;
          default_bond_weeks?: number;
          default_bill_split_mode?: BillSplitMode;
          prorate_move_in?: boolean;
          prorate_move_out?: boolean;
          wifi_ssid?: string | null;
          wifi_password?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      inventory_items: {
        Row: {
          id: string;
          house_id: string;
          room_id: string | null;
          item_name: string;
          category: string | null;
          quantity: number;
          condition: ItemCondition;
          purchase_date: string | null;
          purchase_price: number | null;
          current_value: number | null;
          warranty_expiry: string | null;
          serial_number: string | null;
          photo_path: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          room_id?: string | null;
          item_name: string;
          category?: string | null;
          quantity?: number;
          condition?: ItemCondition;
          purchase_date?: string | null;
          purchase_price?: number | null;
          current_value?: number | null;
          warranty_expiry?: string | null;
          serial_number?: string | null;
          photo_path?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          room_id?: string | null;
          item_name?: string;
          category?: string | null;
          quantity?: number;
          condition?: ItemCondition;
          purchase_date?: string | null;
          purchase_price?: number | null;
          current_value?: number | null;
          warranty_expiry?: string | null;
          serial_number?: string | null;
          photo_path?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      keys: {
        Row: {
          id: string;
          house_id: string;
          key_type: string;
          key_number: string;
          status: KeyStatus;
          room_id: string | null;
          issued_to_tenant: string | null;
          issued_date: string | null;
          returned_date: string | null;
          replacement_cost: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          key_type: string;
          key_number: string;
          status?: KeyStatus;
          room_id?: string | null;
          issued_to_tenant?: string | null;
          issued_date?: string | null;
          returned_date?: string | null;
          replacement_cost?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          key_type?: string;
          key_number?: string;
          status?: KeyStatus;
          room_id?: string | null;
          issued_to_tenant?: string | null;
          issued_date?: string | null;
          returned_date?: string | null;
          replacement_cost?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      lease_participants: {
        Row: {
          id: string;
          lease_id: string;
          tenant_id: string;
          rent_share_percent: number;
          is_primary: boolean;
          moved_in_at: string | null;
          moved_out_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          tenant_id: string;
          rent_share_percent?: number;
          is_primary?: boolean;
          moved_in_at?: string | null;
          moved_out_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          tenant_id?: string;
          rent_share_percent?: number;
          is_primary?: boolean;
          moved_in_at?: string | null;
          moved_out_at?: string | null;
          created_at?: string;
        };
      };
      leases: {
        Row: {
          id: string;
          reservation_id: string | null;
          house_id: string;
          room_id: string | null;
          bed_id: string | null;
          start_date: string;
          end_date: string | null;
          notice_period_weeks: number | null;
          weekly_rent: number;
          bond_amount: number;
          status: LeaseStatus;
          is_couple: boolean;
          move_in_completed: boolean;
          move_out_completed: boolean;
          termination_date: string | null;
          termination_reason: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reservation_id?: string | null;
          house_id: string;
          room_id?: string | null;
          bed_id?: string | null;
          start_date: string;
          end_date?: string | null;
          notice_period_weeks?: number | null;
          weekly_rent: number;
          bond_amount: number;
          status?: LeaseStatus;
          is_couple?: boolean;
          move_in_completed?: boolean;
          move_out_completed?: boolean;
          termination_date?: string | null;
          termination_reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reservation_id?: string | null;
          house_id?: string;
          room_id?: string | null;
          bed_id?: string | null;
          start_date?: string;
          end_date?: string | null;
          notice_period_weeks?: number | null;
          weekly_rent?: number;
          bond_amount?: number;
          status?: LeaseStatus;
          is_couple?: boolean;
          move_in_completed?: boolean;
          move_out_completed?: boolean;
          termination_date?: string | null;
          termination_reason?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      maintenance_photos: {
        Row: {
          id: string;
          ticket_id: string;
          file_path: string;
          file_name: string;
          description: string | null;
          photo_type: string;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          file_path: string;
          file_name: string;
          description?: string | null;
          photo_type?: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          file_path?: string;
          file_name?: string;
          description?: string | null;
          photo_type?: string;
          uploaded_by?: string | null;
          created_at?: string;
        };
      };
      maintenance_tickets: {
        Row: {
          id: string;
          house_id: string;
          room_id: string | null;
          reported_by_tenant: string | null;
          assigned_to: string | null;
          title: string;
          description: string;
          priority: TicketPriority;
          status: TicketStatus;
          responsibility: TicketResponsibility;
          estimated_cost: number | null;
          actual_cost: number | null;
          scheduled_date: string | null;
          completed_date: string | null;
          contractor_name: string | null;
          contractor_contact: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          room_id?: string | null;
          reported_by_tenant?: string | null;
          assigned_to?: string | null;
          title: string;
          description: string;
          priority?: TicketPriority;
          status?: TicketStatus;
          responsibility?: TicketResponsibility;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          scheduled_date?: string | null;
          completed_date?: string | null;
          contractor_name?: string | null;
          contractor_contact?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          room_id?: string | null;
          reported_by_tenant?: string | null;
          assigned_to?: string | null;
          title?: string;
          description?: string;
          priority?: TicketPriority;
          status?: TicketStatus;
          responsibility?: TicketResponsibility;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          scheduled_date?: string | null;
          completed_date?: string | null;
          contractor_name?: string | null;
          contractor_contact?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payment_promises: {
        Row: {
          id: string;
          tenant_id: string;
          lease_id: string;
          promised_amount: number;
          promised_date: string;
          actual_amount: number | null;
          actual_date: string | null;
          is_fulfilled: boolean;
          is_broken: boolean;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          lease_id: string;
          promised_amount: number;
          promised_date: string;
          actual_amount?: number | null;
          actual_date?: string | null;
          is_fulfilled?: boolean;
          is_broken?: boolean;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          lease_id?: string;
          promised_amount?: number;
          promised_date?: string;
          actual_amount?: number | null;
          actual_date?: string | null;
          is_fulfilled?: boolean;
          is_broken?: boolean;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          house_id: string;
          tenant_id: string;
          lease_id: string | null;
          rent_charge_id: string | null;
          amount: number;
          payment_method: PaymentMethod;
          payment_date: string;
          reference: string | null;
          is_advance_payment: boolean;
          is_partial: boolean;
          notes: string | null;
          recorded_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          tenant_id: string;
          lease_id?: string | null;
          rent_charge_id?: string | null;
          amount: number;
          payment_method: PaymentMethod;
          payment_date: string;
          reference?: string | null;
          is_advance_payment?: boolean;
          is_partial?: boolean;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          tenant_id?: string;
          lease_id?: string | null;
          rent_charge_id?: string | null;
          amount?: number;
          payment_method?: PaymentMethod;
          payment_date?: string;
          reference?: string | null;
          is_advance_payment?: boolean;
          is_partial?: boolean;
          notes?: string | null;
          recorded_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rent_charges: {
        Row: {
          id: string;
          lease_id: string;
          lease_participant_id: string | null;
          house_id: string;
          week_start: string;
          week_end: string;
          days_charged: number;
          base_amount: number;
          prorata_amount: number;
          credit_applied: number;
          amount_due: number;
          amount_paid: number;
          status: ChargeStatus;
          due_date: string;
          is_prorated: boolean;
          prorate_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lease_id: string;
          lease_participant_id?: string | null;
          house_id: string;
          week_start: string;
          week_end: string;
          days_charged?: number;
          base_amount: number;
          prorata_amount: number;
          credit_applied?: number;
          amount_due: number;
          amount_paid?: number;
          status?: ChargeStatus;
          due_date: string;
          is_prorated?: boolean;
          prorate_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lease_id?: string;
          lease_participant_id?: string | null;
          house_id?: string;
          week_start?: string;
          week_end?: string;
          days_charged?: number;
          base_amount?: number;
          prorata_amount?: number;
          credit_applied?: number;
          amount_due?: number;
          amount_paid?: number;
          status?: ChargeStatus;
          due_date?: string;
          is_prorated?: boolean;
          prorate_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reservations: {
        Row: {
          id: string;
          house_id: string;
          room_id: string | null;
          bed_id: string | null;
          tenant_id: string;
          start_date: string;
          end_date: string | null;
          weekly_rent: number;
          bond_amount: number;
          status: ReservationStatus;
          deposit_amount: number | null;
          deposit_paid_at: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          room_id?: string | null;
          bed_id?: string | null;
          tenant_id: string;
          start_date: string;
          end_date?: string | null;
          weekly_rent: number;
          bond_amount: number;
          status?: ReservationStatus;
          deposit_amount?: number | null;
          deposit_paid_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          room_id?: string | null;
          bed_id?: string | null;
          tenant_id?: string;
          start_date?: string;
          end_date?: string | null;
          weekly_rent?: number;
          bond_amount?: number;
          status?: ReservationStatus;
          deposit_amount?: number | null;
          deposit_paid_at?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      rooms: {
        Row: {
          id: string;
          house_id: string;
          name: string;
          room_type: RoomType;
          floor: number | null;
          has_ensuite: boolean;
          has_balcony: boolean;
          has_ac: boolean;
          size_sqm: number | null;
          weekly_rent: number | null;
          bond_amount: number | null;
          couple_allowed: boolean;
          couple_surcharge: number | null;
          max_occupants: number;
          description: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          house_id: string;
          name: string;
          room_type: RoomType;
          floor?: number | null;
          has_ensuite?: boolean;
          has_balcony?: boolean;
          has_ac?: boolean;
          size_sqm?: number | null;
          weekly_rent?: number | null;
          bond_amount?: number | null;
          couple_allowed?: boolean;
          couple_surcharge?: number | null;
          max_occupants?: number;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          house_id?: string;
          name?: string;
          room_type?: RoomType;
          floor?: number | null;
          has_ensuite?: boolean;
          has_balcony?: boolean;
          has_ac?: boolean;
          size_sqm?: number | null;
          weekly_rent?: number | null;
          bond_amount?: number | null;
          couple_allowed?: boolean;
          couple_surcharge?: number | null;
          max_occupants?: number;
          description?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tenant_arrears: {
        Row: {
          id: string;
          tenant_id: string;
          lease_id: string;
          total_arrears: number;
          weeks_behind: number;
          status: ArrearsStatus;
          last_reminder_sent: string | null;
          reminder_count: number;
          payment_plan_active: boolean;
          payment_plan_amount: number | null;
          payment_plan_frequency: string | null;
          notes: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          lease_id: string;
          total_arrears?: number;
          weeks_behind?: number;
          status?: ArrearsStatus;
          last_reminder_sent?: string | null;
          reminder_count?: number;
          payment_plan_active?: boolean;
          payment_plan_amount?: number | null;
          payment_plan_frequency?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          lease_id?: string;
          total_arrears?: number;
          weeks_behind?: number;
          status?: ArrearsStatus;
          last_reminder_sent?: string | null;
          reminder_count?: number;
          payment_plan_active?: boolean;
          payment_plan_amount?: number | null;
          payment_plan_frequency?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
      };
      tenant_documents: {
        Row: {
          id: string;
          tenant_id: string;
          document_type: string;
          file_name: string;
          file_path: string;
          file_size: number | null;
          mime_type: string | null;
          uploaded_by: string | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          document_type: string;
          file_name: string;
          file_path: string;
          file_size?: number | null;
          mime_type?: string | null;
          uploaded_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          document_type?: string;
          file_name?: string;
          file_path?: string;
          file_size?: number | null;
          mime_type?: string | null;
          uploaded_by?: string | null;
          notes?: string | null;
          created_at?: string;
        };
      };
      tenants: {
        Row: {
          id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          date_of_birth: string | null;
          nationality: string | null;
          visa_type: string | null;
          visa_expiry: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_relation: string | null;
          employer: string | null;
          occupation: string | null;
          weekly_income: number | null;
          previous_address: string | null;
          previous_landlord_contact: string | null;
          id_type: string | null;
          id_number: string | null;
          id_expiry: string | null;
          status: TenantStatus;
          risk_score: number | null;
          risk_notes: string | null;
          is_blacklisted: boolean;
          blacklist_reason: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          date_of_birth?: string | null;
          nationality?: string | null;
          visa_type?: string | null;
          visa_expiry?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relation?: string | null;
          employer?: string | null;
          occupation?: string | null;
          weekly_income?: number | null;
          previous_address?: string | null;
          previous_landlord_contact?: string | null;
          id_type?: string | null;
          id_number?: string | null;
          id_expiry?: string | null;
          status?: TenantStatus;
          risk_score?: number | null;
          risk_notes?: string | null;
          is_blacklisted?: boolean;
          blacklist_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          date_of_birth?: string | null;
          nationality?: string | null;
          visa_type?: string | null;
          visa_expiry?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relation?: string | null;
          employer?: string | null;
          occupation?: string | null;
          weekly_income?: number | null;
          previous_address?: string | null;
          previous_landlord_contact?: string | null;
          id_type?: string | null;
          id_number?: string | null;
          id_expiry?: string | null;
          status?: TenantStatus;
          risk_score?: number | null;
          risk_notes?: string | null;
          is_blacklisted?: boolean;
          blacklist_reason?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_house_access: {
        Row: {
          id: string;
          user_id: string;
          house_id: string;
          can_edit: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          house_id: string;
          can_edit?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          house_id?: string;
          can_edit?: boolean;
          created_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: UserRole;
          phone: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: UserRole;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: UserRole;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      warnings: {
        Row: {
          id: string;
          tenant_id: string;
          lease_id: string | null;
          house_id: string;
          severity: WarningSeverity;
          rule_violated: string;
          description: string;
          incident_date: string;
          strike_number: number;
          is_acknowledged: boolean;
          acknowledged_at: string | null;
          issued_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          lease_id?: string | null;
          house_id: string;
          severity: WarningSeverity;
          rule_violated: string;
          description: string;
          incident_date: string;
          strike_number?: number;
          is_acknowledged?: boolean;
          acknowledged_at?: string | null;
          issued_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          lease_id?: string | null;
          house_id?: string;
          severity?: WarningSeverity;
          rule_violated?: string;
          description?: string;
          incident_date?: string;
          strike_number?: number;
          is_acknowledged?: boolean;
          acknowledged_at?: string | null;
          issued_by?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      current_occupancy: {
        Row: {
          house_id: string | null;
          house_name: string | null;
          room_id: string | null;
          room_name: string | null;
          room_type: RoomType | null;
          bed_id: string | null;
          bed_number: number | null;
          weekly_rent: number | null;
          lease_id: string | null;
          lease_status: LeaseStatus | null;
          tenant_id: string | null;
          tenant_name: string | null;
          start_date: string | null;
          end_date: string | null;
          is_couple: boolean | null;
        };
      };
      arrears_summary: {
        Row: {
          lease_id: string | null;
          house_id: string | null;
          house_name: string | null;
          tenant_id: string | null;
          tenant_name: string | null;
          email: string | null;
          phone: string | null;
          total_arrears: number | null;
          overdue_weeks: number | null;
          oldest_unpaid_week: string | null;
          arrears_status: ArrearsStatus | null;
        };
      };
    };
    Functions: {
      is_admin: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      has_house_access: {
        Args: { house_uuid: string };
        Returns: boolean;
      };
      can_edit_house: {
        Args: { house_uuid: string };
        Returns: boolean;
      };
      get_user_role: {
        Args: Record<string, never>;
        Returns: UserRole;
      };
      calculate_prorated_rent: {
        Args: { weekly_rent: number; days_occupied: number };
        Returns: number;
      };
      get_week_start: {
        Args: { d: string };
        Returns: string;
      };
    };
    Enums: {
      user_role: UserRole;
      room_type: RoomType;
      bed_status: BedStatus;
      tenant_status: TenantStatus;
      lease_status: LeaseStatus;
      reservation_status: ReservationStatus;
      charge_status: ChargeStatus;
      payment_method: PaymentMethod;
      arrears_status: ArrearsStatus;
      bond_status: BondStatus;
      bill_type: BillType;
      bill_split_mode: BillSplitMode;
      bill_status: BillStatus;
      ticket_priority: TicketPriority;
      ticket_status: TicketStatus;
      ticket_responsibility: TicketResponsibility;
      checklist_type: ChecklistType;
      checklist_status: ChecklistStatus;
      item_condition: ItemCondition;
      key_status: KeyStatus;
      warning_severity: WarningSeverity;
      candidate_status: CandidateStatus;
      alert_type: AlertType;
      alert_priority: AlertPriority;
      audit_action: AuditAction;
      expense_category: ExpenseCategory;
    };
  };
};

// Enum Types
export type UserRole = 'admin' | 'manager' | 'maintenance';
export type RoomType = 'private' | 'shared';
export type BedStatus = 'available' | 'occupied' | 'reserved' | 'maintenance';
export type TenantStatus = 'active' | 'inactive' | 'blacklisted';
export type LeaseStatus = 'draft' | 'active' | 'ending' | 'ended' | 'broken';
export type ReservationStatus = 'pending' | 'confirmed' | 'cancelled' | 'converted';
export type ChargeStatus = 'pending' | 'partial' | 'paid' | 'overdue' | 'waived';
export type PaymentMethod = 'bank_transfer' | 'cash' | 'card' | 'other';
export type ArrearsStatus = 'current' | 'late' | 'reminder_sent' | 'payment_plan' | 'default';
export type BondStatus = 'pending' | 'received' | 'partial' | 'refunded' | 'forfeited';
export type BillType = 'electricity' | 'gas' | 'water' | 'internet' | 'council_rates' | 'insurance' | 'other';
export type BillSplitMode = 'included' | 'equal_per_occupant' | 'per_bed' | 'prorata_days' | 'flat_weekly_per_person';
export type BillStatus = 'pending' | 'allocated' | 'paid';
export type TicketPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TicketStatus = 'open' | 'in_progress' | 'waiting_parts' | 'completed' | 'cancelled';
export type TicketResponsibility = 'landlord' | 'tenant' | 'shared';
export type ChecklistType = 'move_in' | 'move_out';
export type ChecklistStatus = 'pending' | 'in_progress' | 'completed';
export type ItemCondition = 'new' | 'good' | 'fair' | 'poor' | 'damaged' | 'missing';
export type KeyStatus = 'available' | 'issued' | 'lost' | 'replaced';
export type WarningSeverity = 'verbal' | 'written' | 'final';
export type CandidateStatus = 'new' | 'screening' | 'approved' | 'rejected' | 'waitlist';
export type AlertType = 'occupancy' | 'arrears' | 'maintenance' | 'bills' | 'lease_expiry' | 'vacancy';
export type AlertPriority = 'info' | 'warning' | 'critical';
export type AuditAction = 'create' | 'update' | 'delete';
export type ExpenseCategory = 'maintenance' | 'utilities' | 'supplies' | 'insurance' | 'council' | 'mortgage' | 'management' | 'other';

// Helper types for table rows
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Convenient aliases
export type User = Tables<'users'>;
export type House = Tables<'houses'>;
export type Room = Tables<'rooms'>;
export type Bed = Tables<'beds'>;
export type Tenant = Tables<'tenants'>;
export type TenantDocument = Tables<'tenant_documents'>;
export type Reservation = Tables<'reservations'>;
export type Lease = Tables<'leases'>;
export type LeaseParticipant = Tables<'lease_participants'>;
export type RentCharge = Tables<'rent_charges'>;
export type Payment = Tables<'payments'>;
export type PaymentPromise = Tables<'payment_promises'>;
export type TenantArrears = Tables<'tenant_arrears'>;
export type Bond = Tables<'bonds'>;
export type Bill = Tables<'bills'>;
export type BillAllocation = Tables<'bill_allocations'>;
export type Expense = Tables<'expenses'>;
export type MaintenanceTicket = Tables<'maintenance_tickets'>;
export type MaintenancePhoto = Tables<'maintenance_photos'>;
export type Checklist = Tables<'checklists'>;
export type ChecklistItem = Tables<'checklist_items'>;
export type InventoryItem = Tables<'inventory_items'>;
export type CleaningRoster = Tables<'cleaning_roster'>;
export type HouseRulesVersion = Tables<'house_rules_versions'>;
export type Warning = Tables<'warnings'>;
export type Key = Tables<'keys'>;
export type Candidate = Tables<'candidates'>;
export type Alert = Tables<'alerts'>;
export type AuditLog = Tables<'audit_logs'>;
export type UserHouseAccess = Tables<'user_house_access'>;
